### ISSUE TITLE
All emails are invalid

### ISSUE THREAD

**Issue by gsingh93** [y0k4i-1337/checkmail#1]
Does the approach this script uses of checking for the `COMPASS` cookie still work? I've tried this with my own account and it says it's invalid:
```
poetry run ./checkmail.py -u <myaccount> -v
```

I did remove the `cchardet` dependency (which seemed to be unused) and ran `poetry update` in order to get it to work with Python 3.12, but I don't think these dependency updates would have broken this.

**Comment by y0k4i-1337** [comment]
@gsingh93 It hasn't been working for some time. The endpoint works differently by now.
